### ISSUE TITLE
Feature request: Undo clicks

### ISSUE THREAD

**Issue by ckrf** [persts/DotDotGoose#11]
Thanks so much for this wonderful tool!

As far as I can tell, if I click twice on an object or click in the wrong place, there's no way to undo the error without starting over. It would be nice to be able to Ctrl-Z or (for example) right-click to remove a dot.

**Comment by persts** [comment]
@ckrf there is no Ctrl-Z yet and may never be. But if you:
** Press and hold the Shift key then left-click and drag the mouse to draw a box around the point(s) you would like
to delete.
**Once you release the mouse button the selected points will be highlighted with a red halo.
** Press the Delete key to remove the points.
No need to "start over"

**Comment by persts** [comment]
But I agree, It would be a nice enhancement.

**Comment by ckrf** [comment]
Ah perfect, that hits the spot. Thanks so much for the quick response.

**Comment by persts** [comment]
Undo and redo support has been added to version 1.6.0
