### ISSUE TITLE
Feature Request: Export metadata into json format

### ISSUE THREAD

**Issue by tejasri19** [persts/DotDotGoose#13]
@persts JSON format is very much needed for training deep learning models.

**Comment by persts** [comment]
@tejasri19 Can you provide a little more detail of what you are requesting? The .pnt file is a JSON object.

**Comment by tejasri19** [comment]
@persts Does json file has location coordinates of region of interest?

**Comment by persts** [comment]
@tejasri19 Sorry for the delayed response. Totally missed that you had replied. DDG does not have a notion of a region of interest. the .pnt file just holds the the pixel coordinates for each dot. You can find the scheme for the pnt file in at the end of the Quick Guide. The chip export option allows you to define the width an height of a box centered on the points to generate sub images but that will only be helpful if your targets are generally of equal size and shape.
