### ISSUE TITLE
Feature Request: Saving images after dotting

### ISSUE THREAD

**Issue by dottingbirds** [persts/DotDotGoose#14]
Is there a way to save the image other than a screen shot? Preferably in jpeg or similar. Thanks!

**Comment by persts** [comment]
@dottingbirds this would be a good plugin idea for version 2.

For now, you could use the export point feature and then load the image and csv into something like QGIS. The points will be in pixel coordinates so they will overlay on the image just like they do in DDG. From there you could layout and export your "map" to any size you need.

**Comment by persts** [comment]
Added to version 1.6.0.
