### ISSUE TITLE
Rotating images

### ISSUE THREAD

**Issue by Psych0Kitty** [persts/DotDotGoose#15]
Hi, 

Is there a way of rotating images in the app? My images revert to upside down when dragged into the app.

Or any other solution to this issue?

**Comment by persts** [comment]
@Psych0Kitty At the moment there is not. The most straight forward approach would be to just save the images in the correct orientation as the images should also be upside down in most other image editing and viewing software. On some OSes and image preview programs there is a way to "soft rotate" images which does not actually change the underlying image data. Nonetheless, I am a bit curious. If you would be able to share a sample image or explain more about how the images were collected please click the Contact Us button on the download page (https://biodiversityinformatics.amnh.org/open_source/dotdotgoose/) so I can reach out to you by email.
