### ISSUE TITLE
Feature request: support for georeference images/orthomosaic

### ISSUE THREAD

**Issue by ThomasMattern** [persts/DotDotGoose#16]
The app has been used to count birds from georeferenced images (https://eprints.utas.edu.au/46914/1/150550%20-%20Erect-crested%20penguins%20on%20the%20Bounty%20Islands.pdf). The app would greatly benefit from the option to export the resulting point data using coordinates from georeference images.

**Comment by persts** [comment]
@ThomasMattern I 100% agree. It was something we spent a good bit of time discussing prior to initial release, however, we also thought it may be more of an edge case than a general need and after 3.5 years you are only the 3rd person to contact me about it. 

It would be rather easy to implement this as a feature but it would add a number of dependencies, that few people need, and make packaging the executables a good bit more complicated than it already is. 

I do think a tutorial on how to georeference / transform the pixel coordinates in a something like QGIS or the development of a stand-alone app / pipeline is worthwhile however. If you could go back to the [download page](https://biodiversityinformatics.amnh.org/open_source/dotdotgoose/) and hit the "Contact Us" so we could schedule a call I would be grateful and hope we can connect and find a useful solution.

**Comment by persts** [comment]
The ability to export geographic coordinates has been added as a command line script and can be found in 
https://github.com/persts/DotDotGoose/tree/main/extra_tools
