### ISSUE TITLE
Translation of DotDotGoose

### ISSUE THREAD

**Issue by A-d-r-i** [persts/DotDotGoose#17]
Hello,

I use DDG a lot and I would really like to help spread it by translating it into French. For now I just [forked](https://github.com/A-d-r-i/DotDotGoose-fr) the repository but maybe you can set up a system like Weblate, Transifex or Crowdin?

During my translation tests, I am confronted with two problems:

- the icons are not displayed because they are not present in the repository - is it therefore possible to add them?
- when I want to export the chips I get an error:
![image](https://user-images.githubusercontent.com/27277698/207304097-ff406546-b7c4-49d0-8260-10f73dd697ff.png)

Do you have any idea regarding this?

Thanks in advance! 😊

**Comment by persts** [comment]
@A-d-r-i Thanks for catching the missing icons, this was due to a change from Qt5 to Qt6. I will get the icons added to the repo soon. 

Regarding translation, Qt has a built in translation ability. I would love to see this done, but need to make some changes to the code base. Then I can generate a .ts file which can be edited with Qt Linguist and the translation can be done by anyone regardless of programming experience. This would hopefully encourage others to come forward and help translate DDG into even more languages. 

If you are willing to help, I can copy the translations you have already done in the fork into the .ts file, then you would only need to review and make any final translations. This is going to take me a week or two to complete. 

I will also look into the chip export issue.

**Comment by A-d-r-i** [comment]
Thank you very much for your answer ! With the icons I could thus test the compatibility of the text+icon on the interface.

The translation is almost finished on my side I think (DDG + doc), you can use it without problem! And of course do not hesitate to ask for my help if needed.

**Comment by persts** [comment]
@A-d-r-i Make a new clone of the repo. I have added internationalization support, fixed the chip export, and added an additional export type.

It should detect your language based on the locale settings of your computer, but there is also a way to manually select the language, which requires a restart of the program as I don't see any way to dynamically change the language on the fly.

In the translations directory there are (only one right now) .ts files. These are built with the pylupdate6 utility from the ui and py files. The .ts files can be edited with Qt Linguist / QtCreator. No programming skills are needed. I have copied most of your translations over and will ask you to review/update at some point soon, but I still need to add a few extra things that will likely add additional entries to the .ts files. I hope to complete the remaining updates by the end of next week.

**Comment by A-d-r-i** [comment]
Oh wow! Thank you very much for your speed and efficiency Peter!

Everything works perfectly on my side: icons, chips and other exports...
Qt Linguist is installed, I'm waiting for your confirmation to finish the translations and I'll send you all that (with a pull request?).

---
Subsidiary question, I have a little trouble translating "chips" into French. I've defined this as "details", it seems a little too broad to me but I can't find anything more specific.

To be more clear, "Export Image Chips" is translated with the equivalent of "Export image details".
Is it okay for you?

**Comment by persts** [comment]
@A-d-r-i I think all of the UI and message generating changes are done. So you can move forward with the translation. A pull request is fine and feel free to update the entry in the about_dialog.py if you want something different. 

re: chips...hmmm
sub-images 
image subsets
image fragments
image pieces
clipped images
cropped images

**Comment by A-d-r-i** [comment]
Great ! I'll work on doing that in the next few days then. Thanks for the attention in about_dialog, it's perfect! 😊

Congratulations for the new features and quite simply for this application that I use very regularly (ornithologist I regularly count large groups of birds).

Perfect for the details of "chips" I will find an equivalent!

**Comment by A-d-r-i** [comment]
Done for translation! 😎 The pull request is requested.
Normally everything is good, I could not test through python because surprisingly it does not take into account the file. I have the impression that the current translation comes from the file `./i18n/ddg_fr.qm`.

Maybe an idea to keep in mind: add the DotDotGoose icon to the program to replace the classic one (on windows in particular) :
![image](https://user-images.githubusercontent.com/27277698/208064476-109058d7-b7b4-4f78-8666-f02ed7c6e17b.png)

**Comment by persts** [comment]
Yes the .ts file have to be compiled. 

lrelease translations/ddg_fr.ts -qm i18n/ddg_fr.qm

I added the window icon. I hope to bundle and release a new binary the first week of January. Thanks again for all the help.
