### ISSUE TITLE
Malware Detected - App not working

### ISSUE THREAD

**Issue by SpaceByul** [persts/DotDotGoose#20]
I downloaded it today to help with a cell count, but when I went to extract the file, my antivirus detected a Trojan. My girlfriend had been using it for a few days, but today it was no longer possible to put anything on without the app simply closing.

The app was speeding up her work, these manual counts are a nightmare and time consuming. I can't understand how it just stopped like that.
![TROJAN](https://user-images.githubusercontent.com/122475974/211881184-11c47bca-6e9b-44ca-92c8-2e0dd499178d.png)

**Comment by persts** [comment]
@SpaceByul  We have had a few other reports of this recently and specifically with Avast. 

We will be releasing a new version, hopefully next week (with new features & language translation), that is signed with a security certificate which should help. However, only the Windows version will be signed in the next release. If you need a solution sooner, you can contact me directly (email in my profile).

I will leave this open for now until we officially release version 1.6.0

**Comment by persts** [comment]
Version 1.6.0 has been released. It is a signed .exe file which should help prevent false positives from virus/malware scanners.
