### ISSUE TITLE
Is it possible to compare two images side by side.

### ISSUE THREAD

**Issue by Angel-Popa** [persts/DotDotGoose#22]
Hi, 

Thank you for the excellent tool. I was wondering if there is a way to place two images side by side (T0, T1), that way, I can count on both images at once. 

Cheers, 
AP

**Comment by persts** [comment]
You could stitch the two images together side-by-side then load them into DDG, but I am guessing you would still want to have the point counts to be reported separately as it two images.

To be honest, I am having a difficult time trying to envision a situation where side by side images would be more helpful than just toggling back and forth between two images in a stack. I could see the possibility of a slider so you could load registered images pairs and swipe between sections of the two images to look for change. However, that is really beyond the core intention of DDG.
