### ISSUE TITLE
make color space stretching optional

### ISSUE THREAD

**Issue by anbrain3** [persts/DotDotGoose#23]
Artificially modifying the color space of the image can have a negative impact for some applications. Can this be made optional?

**Comment by persts** [comment]
@anbrain3 It could, but this seems like a edge case. What types of images do you have where this causes an issue?

**Comment by anbrain3** [comment]
We're using the application to mark cells in histological images rather than natural images, which I admit is outside it's intended design. I'm also happy to fork and build a version separately for my use case, in which case I was wondering if you have build instructions anywhere. Thanks.

**Comment by persts** [comment]
Are these indexed color images? Would you be able to share an example with me or point me toward downloadable example? My email is in my profile.

**Comment by persts** [comment]
@anbrain3 Image enhancement is controlled by check box now, off by default v1.7.0. Will probably bundle a new executable in the next week or two.
