### ISSUE TITLE
Important Question!!!

### ISSUE THREAD

**Issue by JookBoosly** [persts/DotDotGoose#24]
So I'm writing a research paper on the usage of drones in accounting. Basically auditors take photos of inventory using the drones and  upload images to DotDotGoose. One concern I wanna clear up in my paper is the security. Since this is a free service, is there guarantee that uploaded photos can't be stolen or shared? Just bc internal controls are a big importance in accounting. If someone could point me to a place I can read up on security policies or has the specific answer I would be so grateful!!

**Comment by persts** [comment]
DotDotGoose is a desktop application. It is not a web-based tool.

**Comment by JookBoosly** [comment]
Perfect thank you!!
