### ISSUE TITLE
Grouping points

### ISSUE THREAD

**Issue by ryantheleach** [persts/DotDotGoose#25]
It would be nice to be able to group points to track sizes of groups / herds, and get the counts of individuals in a herd.

**Comment by persts** [comment]
@ryantheleach I may not be understanding what you mean by group points, but your class names are already a grouping. If you labeled your points: herd-1-adult-female, herd-1-adult-male, herd-2-adult-female, herd-2-adult-male... just export your counts and sum the columns that belong to herd-1 for a total herd size. This assumes you don't have multiple images of the same herd that contain the same individuals. If you did, you would have to mosaic the individual images before loading them into DDG.
