### ISSUE TITLE
Updating points file to include new images

### ISSUE THREAD

**Issue by alfurb** [persts/DotDotGoose#26]
In some cases, I have already started counting in a folder when new data arrives (images) arrive. I have not found a way to update the interface to include those as well. Instead, I put the new images into another folder and count them separately.
It would be very useful to have a button that updates the points file in such a way to include the new images, and possibly notify if some images are missing while present in the points file.

**Comment by persts** [comment]
@alfurb you should be able to put the new data into an existing folder, load an existing .pnt file, then drag the new data from the folder onto the image display area. 

I agree, however, that it would be good to have some functionality to check the working directory for new or missing data. That should be a fairly easy thing to implement. I will add it to the enhancement list but I don't know exactly when it will get implemented.

**Comment by persts** [comment]
@alfurb @rascully enhancement pushed to the main branch (1.7.0). Scans directory on loading pnt file for all images and will highlight in red missing images that have entries in pnt file. Will probably be bundling an new executable in the next week or two.
