### ISSUE TITLE
KeyError when trying to relabel points

### ISSUE THREAD

**Issue by stefanistrate** [persts/DotDotGoose#28]
Hi,

I'm currently testing DotDotGoose v1.6.0 on macOS and trying to relabel a bunch of points like in the video below, but I'm getting the following error:

```bash
KeyError
  File "ddg/canvas.py", line 484, in relabel_selected_points
```

The error window appears when I press the `r` key. Any idea what's going on?

https://github.com/persts/DotDotGoose/assets/3457859/d58cb3cf-f1f5-492b-ada2-1a0fe19eb589

If it's helpful, here's the image and the points I'm starting with: [TEST.zip](https://github.com/persts/DotDotGoose/files/12378587/TEST.zip)

Thanks,
Ștefan

**Comment by persts** [comment]
@stefanistrate thank you for the very helpful inclusion of a vid and data. Always makes debugging faster. 

I just pushed a fix. Are you running from source or using the bundled app?

**Comment by stefanistrate** [comment]
I was using the bundled app, but I tested the fix now directly from this repo and it works! Thanks so much for the speedy fix.

**Comment by persts** [comment]
Thanks @stefanistrate. The problem only occurred if you tried to rename points to a class that had no points belonging to that class on the current image. I don't know if I am going to re bundle for this small bug alone as we have some other features that will be added soon. If you need a new bundled app for v 1.6.1 on a single platform, feel free to reach out to me directly.
