### ISSUE TITLE
Error in Renaming Point 

### ISSUE THREAD

**Issue by rascully** [persts/DotDotGoose#32]
Dotted points one class
followed instructions to 5.2 Relabeling Points
1. Make a class active by clicking its name in the class editor.
2. Press and hold the Shift key then left-click and drag to draw a box around the point(s) you would like to relabel.
3. Once you release the mouse button the selected points will be highlighted with a red halo.
4. Press the ‘r’ key to relabel the selected points to the active class.

Got the following error: Exception Detected: ValueError   File "ddg\canvas.py", line 482, in relabel_selected_points

**Comment by persts** [comment]
@rascully This has been reported and fixed #28 but we did not bundle a new release just for this bug as we are adding some additional features at the moment. 

To summarize, the problem only occurs if you try to rename points to a class that had no points belonging to that class on the current image. The work around for 1.6.0 would be to drop at least one point for class B then relabel your selected points from class A.

If you can run from source the main branch already has this fix.

**Comment by rascully** [comment]
Thanks!
