### ISSUE TITLE
Overlay export format

### ISSUE THREAD

**Issue by jotakajota** [persts/DotDotGoose#34]
Overlay export saves in .PNG format, not .JPG as listed in the recent enhancements.  Is this to preserve image quality?  One can convert the format later according to documentation needs, though saving to .jpg w/in DDG would be a useful choice.  I've been using a full sensor camera (counting sea lions and birds on coastal rocks) so the .jpg images are big to start with, and .PNG tend to be much larger files.

**Comment by persts** [comment]
@jotakajota really just a typo on my part. Yes, PNG was selected as the default for quality. However, if you just change the extension to .jpg it will save it in that format.
