### ISSUE TITLE
ability to alter brightness, sharpness, and contrast while counting the image

### ISSUE THREAD

**Issue by rascully** [persts/DotDotGoose#35]
USFWS users request the ability to adjust the images contrast and brightness during counting. These settings don't need to be saved and will be adjusted 

Use case: Biologist count rocky islands that have crevasse and shadows that make it difficult to view the birds/nests. So during the counting they shift the brightness, sharpness, contrast on the fly to be able to dot in different regions of the images. They don't need to save the alterations. 

FWS Data Managers would like to be able to contribute to the development of this feature.

**Comment by persts** [comment]
This functionality has been pushed to the main repo and will appear in the 1.7.0 release.
