### ISSUE TITLE
Opening Dot Dot Goose requires a fresh installation each time

### ISSUE THREAD

**Issue by mdjpe** [persts/DotDotGoose#41]
Hi. I recently started using DotDotGoose for the first time (on Ubuntu Jammy). There seems to be no way to start the program except from the command line;  and I get the following error:

![Screenshot from 2024-11-11 06-27-28](https://github.com/user-attachments/assets/9e2a70ea-3540-4c78-9f76-b74058fcf2b3)

To avoid the error, I have to run the installation sequence prior to startup each time: 

![image](https://github.com/user-attachments/assets/14cf6406-57df-491d-8b48-f572cc7e9bb2)

At that point, the program works as expected.

I would prefer to be able to run the program without an internet connection and with a more normal start procedure. Either
an icon, or a clickable start file in the DotDotGoose folder, or by typing DotDotGoose at the command prompt.

Please advise.

**Comment by persts** [comment]
@mdjpe each time you open a new terminal you need to re-activate your virtual environment, e.g.

source ddg-env/bin/activate

If you don't want to activate you virtual environment and launch the DDG manually each time you could just make a script. In the directory where you download DDG and setup your virtual environment, you can create an empty file called launch.sh then populate that file with the following lines:
```bash
#!/bin/bash
source ddg-env/bin/activate
cd DotDotGoose
python main.py
```
Once the file has been edited make it exactitude: 

chmod 777 launch.sh

You can now just double click this file to activate your virtual environment and launch DDG.

**Comment by mdjpe** [comment]
Thank you, Peter. This was very helpful and has resolved the problem.
