### ISSUE TITLE
Fails to Launch on OSX (10.12 Sierra)

### ISSUE THREAD

**Issue by BKane001** [persts/DotDotGoose#7]
OSX file was downloaded. Immediately crashed upon attempt to open from desktop.

**Comment by persts** [comment]
@BKane001 Can you let me know what version of OSX you are using?

**Comment by BKane001** [comment]
@persts 10.12.6

**Comment by persts** [comment]
Thanks @BKane001. Will take a couple of days to find and get a version of Sierra up and running.

**Comment by persts** [comment]
@BKane001 I finally got a copy of 10.12 (Sierra) running. The problem has to do with the GUI framework we are using (Qt5). The version of PyQt5 we are using for the bundled version of DotDotGoose, which was bundled on 10.15, seems to have been compiled for OSX 10.13 so it only seems to work with version 10.13+

Given our limited resources I don't know if I would be able to maintain multiple builds for OSX. It should work just fine if you were able to install the necessary python packages and downloaded the source from GitHub.

**Comment by persts** [comment]
With additional support needed for 11.0 Big Sur and M1 processors, I am unfortunately going to have to close this ticket and say that I will not be be able to add support for 10.12.
