### ISSUE TITLE
Unable to load JPG images on Windows OS 

### ISSUE THREAD

**Issue by geoffblore** [persts/DotDotGoose#9]

**Comment by persts** [comment]
@geoffblore What version of windows are you using? What version if DDG are you using? How were the images captured (drone, camera trap, etc)? Are the images .jp2 images? Are they not loading when you drag-n-drop as well as when you select a folder?

**Comment by geoffblore** [comment]
Hi Peter,

My apologies, I have managed to load a file of JPG images and was
previously trying to click the import button instead of dragging and
dropping the file in the image display!

Thanks,

Geoff
